// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF54lCs3m0mAw8EYcVB5OqeaxtiGQd-3s',
    appId: '1:874867001359:web:e5891bac85c4c2a1fafb7a',
    messagingSenderId: '874867001359',
    projectId: 'nimbus-2k26-7823c',
    authDomain: 'nimbus-2k26-7823c.firebaseapp.com',
    storageBucket: 'nimbus-2k26-7823c.firebasestorage.app',
    measurementId: 'G-MWDW8FZM80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmCs0hL1WUzFrWkB4BnFv398vIp4GejzE',
    appId: '1:874867001359:android:1228b1c93072f2a3fafb7a',
    messagingSenderId: '874867001359',
    projectId: 'nimbus-2k26-7823c',
    storageBucket: 'nimbus-2k26-7823c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ2ySnDWfItBq_5FvZzhJnVLVwWVLB_yc',
    appId: '1:874867001359:ios:7d05675203dd93eefafb7a',
    messagingSenderId: '874867001359',
    projectId: 'nimbus-2k26-7823c',
    storageBucket: 'nimbus-2k26-7823c.firebasestorage.app',
    androidClientId: '874867001359-bs5c6rj00hr7hoiueagv6vvjjvi59t58.apps.googleusercontent.com',
    iosClientId: '874867001359-gcem0fpgkcb1ds57urchosseg9g9kfvq.apps.googleusercontent.com',
    iosBundleId: 'appteam.nimbus.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLuwkLL6TNi8iJAvzmv6DJN0SDDzSf02w',
    appId: '1:4003601570:ios:5a6446efb3441737220bfb',
    messagingSenderId: '4003601570',
    projectId: 'nimbus-2k26-e52e6',
    storageBucket: 'nimbus-2k26-e52e6.firebasestorage.app',
    iosBundleId: 'com.example.nimbus2k26Frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHU5fM7mpPtZricSwxNX1H4ChxpKBrt_Y',
    appId: '1:4003601570:web:a3f70542810c9851220bfb',
    messagingSenderId: '4003601570',
    projectId: 'nimbus-2k26-e52e6',
    authDomain: 'nimbus-2k26-e52e6.firebaseapp.com',
    storageBucket: 'nimbus-2k26-e52e6.firebasestorage.app',
    measurementId: 'G-P93GSP6EHZ',
  );
}