// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHU5fM7mpPtZricSwxNX1H4ChxpKBrt_Y',
    appId: '1:4003601570:web:b617cd8665e59b69220bfb',
    messagingSenderId: '4003601570',
    projectId: 'nimbus-2k26-e52e6',
    authDomain: 'nimbus-2k26-e52e6.firebaseapp.com',
    storageBucket: 'nimbus-2k26-e52e6.firebasestorage.app',
    measurementId: 'G-LZ3KPXGPWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUyMJzQpDGk0PWg8_2bKl28xfAnX4p7Yw',
    appId: '1:4003601570:android:43538af5619931dc220bfb',
    messagingSenderId: '4003601570',
    projectId: 'nimbus-2k26-e52e6',
    storageBucket: 'nimbus-2k26-e52e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLuwkLL6TNi8iJAvzmv6DJN0SDDzSf02w',
    appId: '1:4003601570:ios:fa94f53c502bbf6a220bfb',
    messagingSenderId: '4003601570',
    projectId: 'nimbus-2k26-e52e6',
    storageBucket: 'nimbus-2k26-e52e6.firebasestorage.app',
    iosBundleId: 'com.appteam.nimbus2k26frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLuwkLL6TNi8iJAvzmv6DJN0SDDzSf02w',
    appId: '1:4003601570:ios:5a6446efb3441737220bfb',
    messagingSenderId: '4003601570',
    projectId: 'nimbus-2k26-e52e6',
    storageBucket: 'nimbus-2k26-e52e6.firebasestorage.app',
    iosBundleId: 'com.example.nimbus2k26Frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHU5fM7mpPtZricSwxNX1H4ChxpKBrt_Y',
    appId: '1:4003601570:web:a3f70542810c9851220bfb',
    messagingSenderId: '4003601570',
    projectId: 'nimbus-2k26-e52e6',
    authDomain: 'nimbus-2k26-e52e6.firebaseapp.com',
    storageBucket: 'nimbus-2k26-e52e6.firebasestorage.app',
    measurementId: 'G-P93GSP6EHZ',
  );
}
